### ISSUE TITLE
Allow creating empty file to copy/paste search results, in order to do subsearch

### ISSUE THREAD

**Issue by VandeWalleUriah** [ZamanKwinten/jlogg#4]
I can see that you can currently save search results, but it would be more optimal if we can copy our search result, create new file and paste the search result inside that new document, so that we can do a kind of subsearch.

Alternatively, would also be nice if we can search the search results.
So you do an initial search, and then there's another search that let's you scan you searchs results, without having to push them to another file.

Use case:
Search everything related to specific workflow ID, after which you search for "error" inside the workflow related search results.

**Comment by ZamanKwinten** [comment]
The idea behind the tool is that it can only read files, not really modify/create new ones (this makes it so that some assumptions could be made to reduce the memory footprint). 

To perform sub searches the suggested flow would  be to save your current search results as a temporary file, and then search within that temporary file. 

That being said the current saving of search results is quite slow, that can probably be optimized a bit.

**Comment by ZamanKwinten** [comment]
Saving of search results has been optimized. 
My current benchmark is a search result of ~ 3 million lines takes 20-30s to save.
